language: ruby

before_script:
  - psql -c "create user owla with createdb login password 'owla1234';" -U postgres
  - psql -c "alter user owla with superuser;" -U postgres

script:
  - bundle exec rake db:drop
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  - bundle exec rake

rvm:
  - 2.3.1
notifications:
  email:
    recipients:
      - livreluan@gmail.com

branches:
  only:
    - master
    - devel

addons:
    code_climate:
            repo_token: 5891b1f77d783db65a29ab9ded1afd855b25cb15c9b4716f3b8f14757b7ed8a4

notifications:
  slack: crabsolutions:7v5QgcE6EeDv2gtP4C9r15si

services:
  - postgresql
